"""Compliance report generation.

Renders a stored scan as an inspection report in two formats:

* **PDF**  - the record an inspector files or serves. Fixed layout, not meant
  to be altered after issue.
* **DOCX** - the same report as an editable document, so an officer can add
  observations, correct a field the OCR misread, or adapt the wording before
  issuing it.

Both are built from the same `_ReportModel`, so the two formats cannot drift
apart in content.
"""

from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from typing import Any

log = logging.getLogger(__name__)

VERDICT_LABEL = {
    "compliant": "COMPLIANT",
    "partial": "PARTIALLY COMPLIANT",
    "non_compliant": "NON-COMPLIANT",
    "needs_review": "NEEDS REVIEW",
}

# Reserved colour per verdict, in the PDF's RGB space.
VERDICT_RGB = {
    "compliant": (0.11, 0.51, 0.26),
    "partial": (0.72, 0.47, 0.05),
    "non_compliant": (0.70, 0.13, 0.13),
    "needs_review": (0.30, 0.35, 0.45),
}

SEVERITY_ORDER = {"critical": 0, "major": 1, "minor": 2, "info": 3}

FIELD_LABELS = [
    ("commodity_name", "Common / generic name"),
    ("manufacturer", "Manufacturer / packer / importer"),
    ("net_quantity", "Net quantity"),
    ("mrp", "Retail sale price"),
    ("manufacture_date", "Date of manufacture / packing"),
    ("expiry_date", "Best before / use by"),
    ("consumer_care", "Consumer care"),
    ("country_of_origin", "Country of origin"),
    ("batch_number", "Batch / lot number"),
    ("fssai_licence", "FSSAI licence"),
]

DISCLAIMER = (
    "This report is generated by the WellPack Auto-Compliance Check System from "
    "an automated reading of a photographed label. Optical character recognition "
    "and automated analysis can misread a declaration. It is decision-support for "
    "a Legal Metrology officer and is not by itself a determination of "
    "contravention under the Legal Metrology Act, 2009."
)


class _ReportModel:
    """The content of a compliance report, independent of output format."""

    def __init__(self, scan: Any) -> None:
        self.scan_id = str(getattr(scan, "id", "") or "")
        self.created_at = getattr(scan, "created_at", None) or datetime.now(timezone.utc)
        self.product_name = getattr(scan, "product_name", None) or "Unidentified commodity"
        self.verdict = getattr(scan, "verdict", None) or "needs_review"
        self.score = float(getattr(scan, "compliance_score", 0) or 0)
        self.confidence = float(getattr(scan, "confidence", 0) or 0)
        self.hallucination = float(getattr(scan, "hallucination_coefficient", 0) or 0)
        self.engine = getattr(scan, "engine", None) or "unknown"
        self.latency_ms = getattr(scan, "latency_ms", None)
        self.source = getattr(scan, "source", None) or "consumer"
        self.scanned_by = getattr(scan, "scanned_by", None)
        self.fields = dict(getattr(scan, "extracted_fields", None) or {})
        self.physical = dict(getattr(scan, "physical_analysis", None) or {})
        self.violations = sorted(
            list(getattr(scan, "violations", None) or []),
            key=lambda v: SEVERITY_ORDER.get(v.get("severity", "minor"), 4),
        )
        self.citations = list(getattr(scan, "citations", None) or [])
        self.reasoning = getattr(scan, "reasoning", None) or ""
        self.ocr_text = getattr(scan, "ocr_text", None) or ""

    @property
    def verdict_label(self) -> str:
        return VERDICT_LABEL.get(self.verdict, self.verdict.upper())

    @property
    def issued(self) -> str:
        return self.created_at.strftime("%d %B %Y, %H:%M UTC")

    def declarations(self) -> list[tuple[str, str, str]]:
        """(label, value, status) for each mandatory declaration."""
        recovered = set(self.fields.get("recovered_by_llm") or [])
        rows: list[tuple[str, str, str]] = []
        for key, label in FIELD_LABELS:
            value = self.fields.get(key)
            if value in (None, "", []):
                rows.append((label, "Not detected", "Absent"))
            else:
                status = "Recovered from OCR" if key in recovered else "Present"
                rows.append((label, str(value), status))
        return rows

    def quality_notes(self) -> list[str]:
        notes: list[str] = []
        if not self.physical.get("quality_ok", True):
            notes.append(str(self.physical.get("quality_message") or "Capture quality is degraded."))
        count = self.physical.get("uncertain_region_count") or 0
        if count:
            notes.append(
                f"{count} text region(s) were read with low OCR confidence; the "
                "declarations they contain should be confirmed visually."
            )
        if self.fields.get("recovered_by_llm"):
            notes.append(
                "The following declarations were not matched by the pattern extractor "
                "but were found in the OCR text on review: "
                + ", ".join(str(f).replace("_", " ") for f in self.fields["recovered_by_llm"])
                + "."
            )
        if self.hallucination > 0.35:
            notes.append(
                f"Grounding drift is elevated ({self.hallucination:.2f}); verify the "
                "cited clauses against the source rules before acting on this report."
            )
        if not notes:
            notes.append("No capture-quality or grounding concerns were recorded.")
        return notes


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------

def build_pdf(scan: Any) -> bytes:
    """Render the scan as a fixed-layout PDF inspection report."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable, KeepTogether, PageBreak, Paragraph, SimpleDocTemplate,
        Spacer, Table, TableStyle,
    )

    model = _ReportModel(scan)
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"Compliance report - {model.product_name}",
        author="WellPack Auto-Compliance Check System",
        subject="Legal Metrology (Packaged Commodities) Rules, 2011",
    )

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=17, leading=21,
                                spaceAfter=2, alignment=TA_LEFT),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=9, leading=12,
                              textColor=colors.HexColor("#555555")),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontSize=11.5, leading=14,
                             spaceBefore=12, spaceAfter=5,
                             textColor=colors.HexColor("#1a2b45")),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=9.2, leading=13),
        "small": ParagraphStyle("sm", parent=base["Normal"], fontSize=7.8, leading=10.5,
                                textColor=colors.HexColor("#444444")),
        "mono": ParagraphStyle("m", parent=base["Normal"], fontName="Courier",
                               fontSize=7.2, leading=9.5),
    }

    def esc(value: Any) -> str:
        return (str(value).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;"))

    story: list[Any] = []

    # --- header ---
    story.append(Paragraph("Legal Metrology Compliance Report", styles["title"]))
    story.append(Paragraph(
        "Packaged Commodities Rules, 2011 &middot; WellPack Auto-Compliance Check System",
        styles["sub"],
    ))
    story.append(Spacer(1, 5))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#c8ced8")))
    story.append(Spacer(1, 9))

    # --- verdict banner ---
    rgb = VERDICT_RGB.get(model.verdict, VERDICT_RGB["needs_review"])
    verdict_colour = colors.Color(*rgb)
    banner = Table(
        [[
            Paragraph(f"<b>{esc(model.verdict_label)}</b>",
                      ParagraphStyle("v", parent=styles["body"], fontSize=14,
                                     leading=17, textColor=colors.white)),
            Paragraph(
                f"<font color='white'>Compliance score <b>{model.score:g}</b>/100<br/>"
                f"Analysis confidence {model.confidence:.0%}</font>",
                ParagraphStyle("vr", parent=styles["small"], textColor=colors.white,
                               fontSize=8.5, leading=11.5),
            ),
        ]],
        colWidths=[105 * mm, 69 * mm],
    )
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), verdict_colour),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(banner)
    story.append(Spacer(1, 10))

    # --- metadata ---
    meta = [
        ["Scan reference", model.scan_id or "-", "Issued", model.issued],
        ["Commodity", model.product_name[:60], "Captured via", model.source],
        ["Analysis engine", model.engine[:40],
         "Inspector", model.scanned_by or "Not recorded"],
    ]
    meta_table = Table(meta, colWidths=[30 * mm, 57 * mm, 26 * mm, 61 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8.2),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
        ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#555555")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_table)

    # --- findings ---
    story.append(Paragraph("1. Findings", styles["h2"]))
    if model.violations:
        rows = [["#", "Severity", "Rule", "Contravention"]]
        for i, v in enumerate(model.violations, 1):
            detail = esc(v.get("message", ""))
            observed, expected = v.get("observed"), v.get("expected")
            if observed:
                detail += f"<br/><font size=7 color='#666666'>Observed: {esc(observed)}</font>"
            if expected:
                detail += f"<br/><font size=7 color='#666666'>Required: {esc(expected)}</font>"
            rows.append([
                str(i),
                esc(v.get("severity", "")).upper(),
                esc(v.get("rule_number", "")),
                Paragraph(detail, styles["small"]),
            ])
        table = Table(rows, colWidths=[8 * mm, 19 * mm, 20 * mm, 127 * mm], repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef1f5")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7.8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c8ced8")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        for i, v in enumerate(model.violations, 1):
            if v.get("severity") == "critical":
                style.append(("TEXTCOLOR", (1, i), (1, i), colors.HexColor("#b32121")))
            elif v.get("severity") == "major":
                style.append(("TEXTCOLOR", (1, i), (1, i), colors.HexColor("#b8780d")))
        table.setStyle(TableStyle(style))
        story.append(table)
    else:
        story.append(Paragraph(
            "No contraventions were recorded against the active rule corpus.",
            styles["body"]))

    # --- analyst summary ---
    if model.reasoning:
        story.append(Paragraph("2. Analyst summary", styles["h2"]))
        story.append(Paragraph(esc(model.reasoning), styles["body"]))

    # --- declarations ---
    story.append(Paragraph("3. Declarations read from the label", styles["h2"]))
    decl_rows = [["Declaration", "Value read", "Status"]]
    decl_rows += [[Paragraph(esc(a), styles["small"]),
                   Paragraph(esc(b)[:160], styles["small"]),
                   Paragraph(esc(c), styles["small"])]
                  for a, b, c in model.declarations()]
    decl = Table(decl_rows, colWidths=[52 * mm, 92 * mm, 30 * mm], repeatRows=1)
    decl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef1f5")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c8ced8")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
    ]))
    story.append(decl)

    # --- legal basis ---
    if model.citations:
        story.append(Paragraph("4. Clauses relied upon", styles["h2"]))
        for c in model.citations[:8]:
            story.append(KeepTogether([
                Paragraph(
                    f"<b>Rule {esc(c.get('rule_number', ''))}</b> &mdash; "
                    f"{esc(c.get('title', ''))} "
                    f"<font size=7 color='#777777'>[{esc(c.get('clause_id', ''))}]</font>",
                    styles["small"]),
                Paragraph(f"<i>{esc(c.get('excerpt', ''))}</i>", styles["small"]),
                Spacer(1, 5),
            ]))

    # --- reviewer notes ---
    story.append(Paragraph("5. Reliability and reviewer notes", styles["h2"]))
    for note in model.quality_notes():
        story.append(Paragraph(f"&bull; {esc(note)}", styles["small"]))

    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#c8ced8")))
    story.append(Spacer(1, 5))
    story.append(Paragraph(esc(DISCLAIMER), styles["small"]))
    story.append(Spacer(1, 14))

    sign = Table(
        [["Inspecting officer", "Designation", "Date"],
         ["", "", ""]],
        colWidths=[62 * mm, 62 * mm, 50 * mm], rowHeights=[6 * mm, 14 * mm],
    )
    sign.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, 0), 7.5),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#666666")),
        ("LINEBELOW", (0, 1), (-1, 1), 0.5, colors.HexColor("#888888")),
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
    ]))
    story.append(sign)

    # --- OCR appendix ---
    if model.ocr_text.strip():
        story.append(PageBreak())
        story.append(Paragraph("Appendix A &mdash; Raw OCR transcript", styles["h2"]))
        story.append(Paragraph(
            "Verbatim text read from the label. Findings above are traceable to this "
            "transcript.", styles["small"]))
        story.append(Spacer(1, 5))
        for line in model.ocr_text.splitlines()[:120]:
            if line.strip():
                story.append(Paragraph(esc(line), styles["mono"]))

    def footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#777777"))
        canvas.drawString(18 * mm, 10 * mm, f"WellPack compliance report &middot; {model.scan_id}"
                          .replace("&middot;", "-"))
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc_.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# DOCX (editable)
# ---------------------------------------------------------------------------

def build_docx(scan: Any) -> bytes:
    """Render the scan as an editable Word document.

    Same content as the PDF, but as ordinary styled paragraphs and tables so an
    officer can revise wording, correct an OCR misread, or add observations
    before issuing it.
    """
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    model = _ReportModel(scan)
    document = Document()

    style = document.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    title = document.add_heading("Legal Metrology Compliance Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    subtitle = document.add_paragraph(
        "Packaged Commodities Rules, 2011 - WellPack Auto-Compliance Check System"
    )
    subtitle.runs[0].font.size = Pt(8.5)
    subtitle.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    verdict_para = document.add_paragraph()
    run = verdict_para.add_run(
        f"{model.verdict_label}  -  score {model.score:g}/100  "
        f"(confidence {model.confidence:.0%})"
    )
    run.bold = True
    run.font.size = Pt(13)
    r, g, b = VERDICT_RGB.get(model.verdict, VERDICT_RGB["needs_review"])
    run.font.color.rgb = RGBColor(int(r * 255), int(g * 255), int(b * 255))

    meta = document.add_table(rows=0, cols=2)
    meta.style = "Light List Accent 1"
    for key, value in [
        ("Scan reference", model.scan_id or "-"),
        ("Issued", model.issued),
        ("Commodity", model.product_name),
        ("Captured via", model.source),
        ("Inspector", model.scanned_by or "Not recorded"),
        ("Analysis engine", model.engine),
    ]:
        cells = meta.add_row().cells
        cells[0].text = key
        cells[1].text = str(value)

    document.add_heading("1. Findings", level=1)
    if model.violations:
        table = document.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        for cell, heading in zip(table.rows[0].cells,
                                 ["#", "Severity", "Rule", "Contravention"]):
            cell.text = heading
            cell.paragraphs[0].runs[0].bold = True
        for i, v in enumerate(model.violations, 1):
            cells = table.add_row().cells
            cells[0].text = str(i)
            cells[1].text = str(v.get("severity", "")).upper()
            cells[2].text = str(v.get("rule_number", ""))
            detail = str(v.get("message", ""))
            if v.get("observed"):
                detail += f"\nObserved: {v['observed']}"
            if v.get("expected"):
                detail += f"\nRequired: {v['expected']}"
            cells[3].text = detail
    else:
        document.add_paragraph(
            "No contraventions were recorded against the active rule corpus."
        )

    if model.reasoning:
        document.add_heading("2. Analyst summary", level=1)
        document.add_paragraph(model.reasoning)

    document.add_heading("3. Declarations read from the label", level=1)
    decl = document.add_table(rows=1, cols=3)
    decl.style = "Table Grid"
    for cell, heading in zip(decl.rows[0].cells, ["Declaration", "Value read", "Status"]):
        cell.text = heading
        cell.paragraphs[0].runs[0].bold = True
    for label, value, status in model.declarations():
        cells = decl.add_row().cells
        cells[0].text = label
        cells[1].text = value[:200]
        cells[2].text = status

    if model.citations:
        document.add_heading("4. Clauses relied upon", level=1)
        for c in model.citations[:8]:
            para = document.add_paragraph()
            head = para.add_run(
                f"Rule {c.get('rule_number', '')} - {c.get('title', '')} "
                f"[{c.get('clause_id', '')}]"
            )
            head.bold = True
            excerpt = document.add_paragraph(str(c.get("excerpt", "")))
            excerpt.runs[0].italic = True
            excerpt.runs[0].font.size = Pt(8.5)

    document.add_heading("5. Reliability and reviewer notes", level=1)
    for note in model.quality_notes():
        document.add_paragraph(note, style="List Bullet")

    document.add_heading("6. Officer observations", level=1)
    placeholder = document.add_paragraph(
        "[Add observations, corrections to any misread declaration, and the action "
        "taken here before issuing this report.]"
    )
    placeholder.runs[0].italic = True
    placeholder.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    document.add_paragraph()
    disclaimer = document.add_paragraph(DISCLAIMER)
    disclaimer.runs[0].font.size = Pt(8)
    disclaimer.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    document.add_paragraph()
    sign = document.add_table(rows=2, cols=3)
    sign.style = "Table Grid"
    for cell, heading in zip(sign.rows[0].cells,
                             ["Inspecting officer", "Designation", "Date"]):
        cell.text = heading
        cell.paragraphs[0].runs[0].bold = True
    for cell in sign.rows[1].cells:
        cell.text = " "

    if model.ocr_text.strip():
        document.add_page_break()
        document.add_heading("Appendix A - Raw OCR transcript", level=1)
        note = document.add_paragraph(
            "Verbatim text read from the label. Findings above are traceable to "
            "this transcript."
        )
        note.runs[0].font.size = Pt(8.5)
        mono = document.add_paragraph()
        run = mono.add_run(model.ocr_text[:6000])
        run.font.name = "Consolas"
        run.font.size = Pt(8)

    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def filename_for(scan: Any, extension: str) -> str:
    """A stable, filesystem-safe download name for a scan's report."""
    import re

    model = _ReportModel(scan)
    slug = re.sub(r"[^A-Za-z0-9]+", "-", model.product_name).strip("-").lower()[:40]
    stamp = model.created_at.strftime("%Y%m%d")
    return f"wellpack-compliance-{slug or 'report'}-{stamp}.{extension}"
